import "@/styles/globals.css";
import React from "react";
import { useRouter } from "next/router";
import { AppCacheProvider } from "@mui/material-nextjs/v13-pagesRouter";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { Roboto } from "next/font/google";
import Layout from "@/components/layout";
import useBearStore from "@/store/useBearStore";
import Head from "next/head";
import { Backdrop, CircularProgress } from "@mui/material";
import { CSSTransition, TransitionGroup } from "react-transition-group"; // Import for transitions

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

const theme = createTheme({
  palette: {},
  typography: {
    fontFamily: roboto.style.fontFamily,
  },
});

export default function App({ Component, pageProps }) {
  const router = useRouter();
  const [loading, setLoading] = React.useState(false);
  const setAppName = useBearStore((state) => state.setAppName);
  const pageName = router.pathname;
  const [key, setKey] = React.useState(pageName); // Key for transition

  React.useEffect(() => {
    console.log("App load", pageName, router.query);
    setLoading(true);
    // Set the app name
    setAppName("VALUE INVESTING SCREENER");
    setLoading(false);
  }, [router, pageName]);

  React.useEffect(() => {
    const handleRouteChange = (url) => {
      setKey(url); // Update key on route change
    };

    router.events.on("routeChangeComplete", handleRouteChange);

    return () => {
      router.events.off("routeChangeComplete", handleRouteChange);
    };
  }, [router]);

  return (
    <React.Fragment>
      <Head>
        <title>{`Application`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppCacheProvider>
        <ThemeProvider theme={theme}>
          <Layout>
            <TransitionGroup>
              <CSSTransition key={key} classNames="page" timeout={300}>
                <Component {...pageProps} />
              </CSSTransition>
            </TransitionGroup>
          </Layout>
        </ThemeProvider>
      </AppCacheProvider>
    </React.Fragment>
  );
}
